# -- RESERVED --
# Define your Job
Train_Dataset: TrainBlender
Val_Dataset: ValBlender
Model: StereoPvn3d
Loss: StereoPvn3dLoss
Metrics:
  - accuracy
Optimizer: Adam
Callbacks: # TO be revised
  - DemoInference
  - ModelCheckpoint
  #- ReduceLROnPlateau
gpus: ['0']# if multiple gpus then distributed training is used
model_fit:
  epochs: 60
mounts:
  - /home/elena/repos/StereoAttention/dataset/blender/blender
# --- ---
# Define Kwargs for modules below

Adam:
  learning_rate: 0.0005
  
TrainBlender:
  batch_size: 1
  root: "/home/elena/repos/StereoAttention/dataset/blender/blender/"
  data_name: stereo_test
  if_pose: true
  cls_type: all
  train_split: 0.9
  use_cache: true
  im_size:
    - 480
    - 640
    
ValBlender: &val_config
  batch_size: 1
  root: "/home/elena/repos/StereoAttention/dataset/blender/blender"
  data_name: stereo_test
  if_pose: true
  cls_type: all
  train_split: 0.9
  use_cache: false
  im_size:
    - 480
    - 640

StereoPvn3d:
  rgb_shape : [640, 480, 3]
  use_disparity: true
  relative_disparity: false
  channel_multiplier: 16 # original: 4
  base_channels: [1,2,4,8,16,32]
  num_pts: 30000
  num_kpt: 8
  num_cls: 6
  num_cpts: 1
  dim_xyz: 3

DemoInference:
  num_validate: 5
  data_cfg: *val_config


StereoPvn3dLoss:
  mse_loss_discount: 0.001
  l1_loss_discount: 0
  ssim_loss_discount: 0.2
  mlse_loss_discount: 0.8
  seg_loss_discount: 0.5
  ssim_max_val: 1.5
  kp_loss_discount: 1
  cp_loss_discount: 1
  sm_loss_discount: 1
  kp_cp_loss_discount: 1
  kp_cp_ofst_loss_discount: 1
