epochs: 100
dataset: 6IMPOSE
num_validate: 7
weights: "checkpoints/TrainE2E_Base_stereopvn_pietro/model_011" 
#weights: "checkpoints/cpsduck (continued)/model_*"
#weights: "checkpoints/lm_cam (continued)/model_*"
#weights: "checkpoints/lm_cam (no-seg loss)/model_*"
freeze: 0

shared: &shared
  # cutoff: 200
  cls_type: cpsduck
  #root: "/home/porlandi/Documents/Dataset/single_img_dataset"
  root: "/home/porlandi/Documents/data"
  batch_size: 8
  use_cache: True
  bbox_noise: 20 # shift by how many pixels
  n_objects_per_image: 5
  if_pose: true



Train6IMPOSE:
  <<: *shared
  train_split: 0.9
  # cutoff: 100
  n_aug_per_image: 1
  add_bbox_noise: false

Val6IMPOSE:
  <<: *shared
  train_split: 0.9
  # cutoff: 10
  n_aug_per_image: 1
  add_bbox_noise: false

Adam:
  learning_rate: 0.00008

StereoPvn3d:
  resnet_input_shape : [144, 192, 3]
  use_disparity: true
  relative_disparity: false
  channel_multiplier: 4 # original: 4
  base_channels: [1,2,4,8,16,32]
  num_pts: 1600
  num_kpt: 8
  num_cls: 1
  num_cpts: 1
  dim_xyz: 3


StereoPvn3dLoss:
  resnet_input_shape : [144,192,3]
  mse_loss_discount: 0.05
  ssim_loss_discount: 50
  mlse_loss_discount: 0.000005
  ssim_max_val: 5
  ssim_filter_size: 11
  ssim_k1: 0.5
  ssim_k2: 1.5
  kp_loss_discount: 30
  cp_loss_discount: 30
  sm_loss_discount: 10
  deriv_loss_discount: 0.0000
  hessian_loss_discount: 0.0000
