epochs: 60
dataset: 6IMPOSE
num_validate: 15
#weights: "checkpoints/TrainE2E/model_32" # this is trained on multi
#weights: "checkpoints/cpsduck (continued)/model_*"
#weights: "checkpoints/lm_cam (continued)/model_*"
#weights: "checkpoints/lm_cam (no-seg loss)/model_*"


shared: &shared
  cls_type: cpsduck
  root: "/home/porlandi/Documents/Dataset"
  batch_size: 4
  use_cache: False
  bbox_noise: 20 # shift by how many pixels
  n_objects_per_image: 20
  if_pose: true



Train6IMPOSE:
  <<: *shared
  train_split: 0.9
  #cutoff: 1000
  n_aug_per_image: 1
  add_bbox_noise: false

Val6IMPOSE:
  <<: *shared
  train_split: 0.1
  #cutoff: 1000
  n_aug_per_image: 1
  add_bbox_noise: false

Adam:
  learning_rate: 0.0005

StereoPvn3d:
  rgb_shape : [640, 480, 3]
  use_disparity: true
  relative_disparity: false
  channel_multiplier: 4 # original: 4
  base_channels: [1,2,4,8,16,32]
  num_pts: 1500
  num_kpt: 8
  num_cls: 1
  num_cpts: 1
  dim_xyz: 3


StereoPvn3dLoss:
  mse_loss_discount: 0.005
  l1_loss_discount: 0
  ssim_loss_discount: 0.5
  mlse_loss_discount: 0.5
  seg_loss_discount: 0.5
  ssim_max_val: 1.5
  ssim_filter_size: 40
  ssim_k1: 0.5
  ssim_k2: 1.5
  kp_loss_discount: 1
  cp_loss_discount: 1
  sm_loss_discount: 1
  kp_cp_loss_discount: 1
  kp_cp_ofst_loss_discount: 1
  
StereoPvn3dMetrics:
  name: "stereo_pvn3d_metrics"
